package com.example.application.backend.repository;

import com.example.application.backend.model.entity.Note;
import java.util.Optional;

/***
 * This interface will be EXTENDED by the regular NoteRepository, so in the Service Layer
 * there will be no need to change the Autowired, and you will be able to keep using
 * private final NoteRepository noteRepository;
 * <p>
 * The NoteRepository will have both: the methods generated by Spring, and our additions
 * <p>
 * This interface will be implemented by CustomNoteJpaRepositoryImpl, so we'll be able
 * to define custom queries with greater control.
 * Either in JPQL, or by directly manipulating the EntityManager 
 * 
 */
public interface CustomNoteJpaRepository {

  Optional<Note> findNoteByTitle(String title);

  /***
   * There is no need to use both of the following methods.
   * Just pick the one with the implementation you like the most
   */
  Note findByIdMandatory(Long id);
  Note findByIdMandatoryAlternative(Long noteId);
    
}
